name = "M_manifest"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[preprocess]
[preprocess.cpp]
macros=["VERSION={version}"] # <== no space in front of first -D
#macros=["NAME={name}","VERSION={version}"] 
#macros=["NAME={name}","VERSION={version}","LICENSE={license}","MAINTAINER={maintainer}",
#"AUTHOR={author}","COPYRIGHT={copyright}","DESCRIPTION={description}",
#"CATEGORIES={categories}","KEYWORDS={keywords}","HOMEPAGE={homepage}","TARGETS={targets}"]

#macros=["NAME={name}","VERSION={version}","LICENSE={license}","MAINTAINER={maintainer}",
#"AUTHOR={author}","COPYRIGHT={copyright}","DESCRIPTION={description}",
#"CATEGORIES={categories}","KEYWORDS={keywords}","HOMEPAGE={homepage}","TARGETS={targets}"]
[[executable]]
name="seeit"
source-dir="app"
main="main.f90"
[executable.dependencies]
