name = "M_manifest"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
keywords = ["fortran","toml","fpm"]
description = "experiments with pre-processing and toml-f"
categories = ["fortran","fpm"]
homepage = ["https://github.com/urbanjost/M_manifest"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[preprocess]
[preprocess.cpp]
macros=["NAME={name}","VERSION={version}","LICENSE={license}","MAINTAINER={maintainer}",
"AUTHOR={author}","COPYRIGHT={copyright}","DESCRIPTION={description}",
"CATEGORIES={categories}","KEYWORDS={keywords}","HOMEPAGE={homepage}","TARGETS={targets}"]

[[executable]]
name="seeit"
source-dir="app"
main="main.f90"
[executable.dependencies]
fpm = { git = "https://github.com/fortran-lang/fpm.git" }
M_io = { git = "https://github.com/urbanjost/M_io.git" }
